export default [
  [
    'Matemática Discreta',
    'Teirua da Adnubustração',
    'Engenharia de Software',
    'Algorítmos e Programação',
    'Arquitetura de Computadores',
    'Seminários I',
    'Ingles I',
  ],
  [
    'Processo de Produção de Software',
    'Linguagem de Programação I',
    'Lógica para Computação',
    'Álgebra Linear',
    'Marketing Digital',
    'Seminários II',
  ],
  [
    'Estrutura de Dados',
    'Linguagem de Programação II',
    'Cálculo DIferencial e Integral I',
    'Requisitos e Modelagem de Software',
    'Interface Humano-Computador',
    'Projeto Integrador I',
  ],
  [
    'Análise e Projeto de Algoritmos',
    'Banco de Dados',
    'Sistemas Operacionais',
    'Probabilidade e Estatística',
    'Design e Arquitetura de Software',
    'Projeto INtegrador II',
  ],
  [
    'Redes e Sistemas Distribuídos',
    'Qualidade de Software',
    'Teste, Verificação e Validação de Software',
    'Desenvolvimento para DIspositivos Móveis',
    'Gestão de Pessoas',
    'Antropologia e Sociologia',
    'Projeto Integrador III',
  ],
  [
    'Gestão de Projetos de Software',
    'Inteligência Artificial',
    'Pesquisa Operacional',
    'Empreendedorismo',
    'Fundamento de Direito Privado',
    'Fábrica de Software I',
    ,
  ],
  [
    'Gerência de Configuração de Software',
    'Gestão e Governança de TI',
    'Fundamentos de Game Design',
    'Fundamentos de Business Inteligence',
    'Eletiva I',
    'TCC I',
    'Educação para Direitos Humanos',
    'Fábrica de Software II',
  ],
  [
    'Segurança e Auditoria de Sistemas',
    'Gerência de Manutenção de Software',
    'Mercado Produto de Software',
    'Eletiva II',
    'TCC II',
    'Direito Ambiental',
  ],
];
